services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: tin
      POSTGRES_PASSWORD: tin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount your SQL file to the init directory
      - ./postgresql.conf:/etc/postgresql/postgresql.conf # Mount the custom config file here
      - ./pg_hba.conf:/etc/postgresql/postgresql.conf.d/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    deploy:
      resources:
        limits:
          memory: 18G # Limit memory to 1GB
          cpus: "2.0" # Limit CPU to 1 core
    restart: always

volumes:
  postgres_data: # Declare the volume here
    driver: local
